source 'https://rubygems.org'
ruby '~> 3.0'

gem 'discordrb', github: 'shardlab/discordrb'
gem 'easy_logging'
gem 'geode'
gem 'http'
gem 'marble_markdown'
gem 'oga'
gem 'rubocop', group: 'development'
gem 'rufus-scheduler'
gem 'tzinfo-data'
